name: sub
on:
  workflow_dispatch:

jobs:
  optional-1:
    runs-on: ubuntu-latest
    needs: compulsory-job
    if: false
    steps:
      - name: optional-step-1
        run: echo "optional step 1"

  optional-2:
    runs-on: ubuntu-latest
    needs: compulsory-job

    steps:
      - name: optional-step-2
        run: echo "optional step 2"
