name: sub
on:
  workflow_call:

jobs:
  optional-1:
    runs-on: ubuntu-latest
    steps:
      - name: optional-step-1
        run: exit 1


  optional-2:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: optional-step-2
        run: echo "optional step 2"
