name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compulsory-job:
    runs-on: ubuntu-latest
    outputs:
      test: 'true'

    steps:
      - name: test-step
        run: echo "testing"

  optional-1:
    runs-on: ubuntu-latest
    needs: compulsory-job
    if: needs.compulsory-job.outputs.test == 'true'

    steps:
      - name: optional-step-1
        run: echo "optional step 1"
      - name: force error
        run: exit 1
        
  optional-2:
    runs-on: ubuntu-latest
    needs: compulsory-job
    if: needs.compulsory-job.outputs.test == 'true'

    steps:
      - name: optional-step-2
        run: echo "optional step 2"
